### ISSUE TITLE
Implement WAL support in v2

### ISSUE THREAD

**Issue by stefanos82** [aaemnnosttv/wp-sqlite-db#20]
Hey @aaemnnosttv, I can see you work on [v2](https://github.com/aaemnnosttv/wp-sqlite-db/tree/v2).

Is it possible to add WAL support in it?

Based on your feedback in #3 I have added it myself and works as expected, at least on standard websites.

I have implemented a simple logic that goes like this:

```php
define('DISALLOW_FILE_EDIT', true);
```
Should be added in `wp-config.php`; its implementation in `db.php` goes as follows:

```php
$GLOBALS['wpdb'] = new WP_SQLite_DB\wpsqlitedb();

    if ( defined( 'ENABLE_SQLITE_WAL' ) && ENABLE_SQLITE_WAL === true ) {
        $GLOBALS['wpdb']->query('PRAGMA journal_mode = WAL');
    } else {
        $GLOBALS['wpdb']->query('PRAGMA journal_mode = DELETE');
    }

```
I have placed it at the very end right before the last closing curly bracket.

I would like to use a better way though than using the `$GLOBAL`.

Any suggestion?

**Comment by aaemnnosttv** [comment]
Hi @stefanos82 – yes, I've started on a v2 which is still somewhat experimental.

I don't see why we can't add support for WAL, it sounds like a good idea 👍 

As for the pragma to enable it, that would be something we would implement internally so you wouldn't have to do that yourself.

Not sure what you're asking exactly about the use of the global. The wpdb instance has to go there for WordPress to use it. You could keep your own reference to it however you want.

**Comment by stefanos82** [comment]
> Not sure what you're asking exactly about the use of the global. The wpdb instance has to go there for WordPress to use it. You could keep your own reference to it however you want.

I'm stupid lol, I completely forgot that `$GLOBALS['wpdb']` is the same as `$wpdb`.

Ignore this last part hahaha :rofl:

**Comment by stefanos82** [comment]
@aaemnnosttv also I would like to suggest the following: install WooCommerce and try to see where it breaks or timeout during navigation around the website, of course without WAL being enabled; I got bitten by it and could not use the website until I enabled WAL.

I'm sure it will reveal lots of problematic parts of code that need improvement.

**Comment by aaemnnosttv** [comment]
This may be something we can add but I think setting the pragma may need to be something we only set when creating the db file (based on a constant, etc). I wouldn't want to put something in place that generates a query on every page load.

**Comment by stefanos82** [comment]
> I wouldn't want to put something in place that generates a query on every page load.

Ah yes, you are right on this one.

**Comment by AxelTheGerman** [comment]
hmm this is interesting. I assume WAL support is also needed to get [litestream](https://litestream.io) to work correct? If so that'd be a huge win!

**Comment by batonac** [comment]
Any reason not to make WAL default on v1? It seems that some are already doing it by adding:
`    $GLOBALS['wpdb']->query('PRAGMA journal_mode = wal;');
`
