### ISSUE TITLE
Question: How to enable WAL if possible?

### ISSUE THREAD

**Issue by stefanos82** [aaemnnosttv/wp-sqlite-db#3]
@aaemnnosttv I have installed WooCommerce plugin and locks the database all the time.

Is there a way to enable WAL with pragma somewhere in `wp-config.php`?

**Comment by aaemnnosttv** [comment]
Looks like it should be possible, although I don't think there is an easy way to do this in the plugin currently. It seems all that's needed would be a call to `$GLOBALS['wpdb']->query('PRAGMA journal_mode = wal;')`. The value should be persisted in the DB, so it shouldn't need to be run on every load.

Can you try that and let me know if that does it for you?

**Comment by stefanos82** [comment]
I will for sure. When shall I try this, at the very end of `db.php`?

**Comment by stefanos82** [comment]
Yep, I placed it right after `$GLOBALS['wpdb'] = new WP_SQLite_DB\wpsqlitedb();` and works amazingly!

It's extremely fast :smile: thank you @aaemnnosttv!

I'm closing this ticket.

Once again, thanks a million mate :100:

**Comment by stefanos82** [comment]
@aaemnnosttv any suggestion how to use `$GLOBALS['wpdb']->query('PRAGMA journal_mode = wal;')` in any other place that cannot be overwritten by `db.php` upgrade?

I have upgraded to the latest version and overwrote the aforementioned line :laughing: 

Please advice, thank you.
