### ISSUE TITLE
possible to use this without composer installation or without composer?

### ISSUE THREAD

**Issue by hiqsociety** [aaemnnosttv/wp-sqlite-db#33]
possible to use this without composer installation or without composer?

**Comment by gschechter** [comment]
This is a 'drop-in' plugin for Wordpress.   The /src/db.php file is the plugin and it would be installed in the /wp-content/ directory ie  /wp-content/db.php

You can install it and automatically keep it updated via composer or you can manually download and install it to a Wordpress installation. 


In wordpress core the load.php -> require_wp_db() function around line 548 looks if /wp-content/db.php exists and if so it loads the db.php 
```	require_once ABSPATH . WPINC . '/wp-db.php';
	if ( file_exists( WP_CONTENT_DIR . '/db.php' ) ) {
		require_once WP_CONTENT_DIR . '/db.php';
	}

**Comment by aaemnnosttv** [comment]
What @gschechter said 😄

As noted in the readme, see the **Quick Start** section 👍 
https://github.com/aaemnnosttv/wp-sqlite-db#quick-start
