### ISSUE TITLE
Interesting suggestion by a WP Core member

### ISSUE THREAD

**Issue by stefanos82** [aaemnnosttv/wp-sqlite-db#39]
Seems like @aristath had suggested the [SQLite support](https://make.wordpress.org/core/2022/09/12/lets-make-wordpress-officially-support-sqlite/) for WordPress.

It would be nice if Ari came here to share some thoughts based on existing feedback we have thus far provided via tickets.

This particular ticket of mine #4 is what interests me the most; I have some customers that sell 15 to 20 items only and would be an overkill to depend on MySQL / MariaDB when I can easily use SQLite.

All in all, I'm very excited to see this suggestion and I would like to see it in WP core!

By the way @aristath,

![image](https://user-images.githubusercontent.com/1777466/189629043-c296ac86-3b53-4d10-82a9-439b06c59041.png)

I have solved this, at least when I tested it locally (see #20), with WAL enabled worked without a problem.

**Comment by aaemnnosttv** [comment]
Is the ask here mostly to enhance the experience of enabling WAL? If so, let's move the conversation to the respective issue(s) 👍

**Comment by stefanos82** [comment]
I asked Aris to provide his feedback here as it's very quiet place comparing `make.wordpress.org` which you need to be registered to join the chat.

Where should this topic be answered, in which repo or forum?
