### ISSUE TITLE
Changing database location

### ISSUE THREAD

**Issue by oleteacher** [aaemnnosttv/wp-sqlite-db#43]
Please forgive me for such a rookie issue. Not a fan of asking questions here, but I am stuck.

"By default, the SQLite database is located in wp-content/database/.ht.sqlite, but you can change this using a few constants."

```
define('DB_DIR', '/absolute/custom/path/to/directory/for/sqlite/database/file/');
define('DB_FILE', 'custom_filename_for_sqlite_database');
```

I assume this goes into wp-config.php and not db.php ?

wp-sqlite-db is a game changer for using WP in classroom environment since we cannot run mySQL.

Thank you!

**Comment by aaemnnosttv** [comment]
> I assume this goes into wp-config.php and not db.php ?

Yes, just like the standard constants for DB credentials. `db.php` is not a file that should be modified 👍 

> wp-sqlite-db is a game changer for using WP in classroom environment since we cannot run mySQL.

Never thought of that, great to hear it! 🙂

**Comment by oleteacher** [comment]
Thank you for replying!
