### ISSUE TITLE
Drop in db.php to fresh installation?

### ISSUE THREAD

**Issue by ph27** [aaemnnosttv/wp-sqlite-db#48]
I'm trying to start a new wordpress 6.1.1 site today, using sqlite instead of mysql.

Steps to recreate:
Downloaded https://wordpress.org/latest.zip
Extracted to root web directory
Downloaded db.php file
Copied db.php file to wp-content directory
Started Wordpress installation by surfing to the site.
Selected language, clicked continue
Prompt about database info appears, click Let's Go!
Database connection form appears, as if a mysql database is expected. Since there is no mysql database, anything I enter into the form results in 'Error establishing database connection'

Checking the directory, there was no wp-content/database directory created. I created it, but this had the same result.

If it matters, I am using nginx and php 8.1 on ubuntu 20.04. Sqlite and sqlite3 are both already installed. I have used the deprecated Sqlite Integration plugin on this same server before, and I remember the installation skipped over the database section.

Did I miss something? What should I have done differently?

Thank you for any help you can provide! :)

**Comment by ph27** [comment]
Sorry, I figured it out. I needed to copy the wp-config-sample.php file to wp-config.php manually, and then the installation proceeded. Sorry!

**Comment by aaemnnosttv** [comment]
This question came up recently and I put together a simple script as a recipe for a fresh install. See https://github.com/aaemnnosttv/wp-sqlite-db/issues/36#issuecomment-1238843052

Closing this out as as there's nothing to address 👍
