### ISSUE TITLE
DESC alias for DESCRIBE?

### ISSUE THREAD

**Issue by stefanos82** [aaemnnosttv/wp-sqlite-db#5]
@aaemnnosttv Lines [3183 to 3186](https://github.com/aaemnnosttv/wp-sqlite-db/blob/master/src/db.php#L3183-L3186) say `DESC` is an alias for `DESCRIBE`.

Does not this conflict with `DESC` for sorting?

As far as I know, both SQLite and MySQL / MariaDB support `EXPLAIN` which for MySQL / MariaDB is a synonym for `DESCRIBE`.

Is there a particular reason we use this alias?

**Comment by aaemnnosttv** [comment]
Hmm, it might? I'm not sure.

This code is from the [original plugin](https://wordpress.org/plugins/sqlite-integration/).

Can you produce a bug using it?

**Comment by stefanos82** [comment]
No, not really but I was wondering why at random times with WAL enabled it kind of hangs for 2-3 seconds and then behaves as if nothing happened.

That was the reason behind my investigation and discovered that peculiar syntax.

**Comment by aaemnnosttv** [comment]
Closing for now. Feel free to reopen if this is indeed a problem 👍
