### ISSUE TITLE
Tagging version with PHP 8.2 support?

### ISSUE THREAD

**Issue by dingo-d** [aaemnnosttv/wp-sqlite-db#51]
Is there anything we can help to speed up the version that will support 8.2? I had to use `master` branch because of failures on the CI regarding composer installers (v1 is the default in the last tagged version).

I keep getting deprecation notices on 8.2

>  Creation of dynamic property WP_SQLite_DB\ObjectArray::$Table is deprecated 

And other properties. I know #50 was merged, but no version was tagged.

Is there a to do list of tasks that should be fixed before new version is released?

**Comment by aaemnnosttv** [comment]
Thanks for the nudge, I'll tag a new release soon 👍

**Comment by dingo-d** [comment]
If you need any kind of help let me know, I have some free time until March so I can help with testing or such 🙂

**Comment by aaemnnosttv** [comment]
Looks like we need to add 8.2 to the test matrix. Feel free to open a PR for that if you'd like?

**Comment by dingo-d** [comment]
Sure, on it 👍🏼
