### ISSUE TITLE
WooCommerce fatal errror

### ISSUE THREAD

**Issue by Torqain3** [aaemnnosttv/wp-sqlite-db#57]
Any idea how to fix this?

Fatal error: Uncaught RuntimeException: Fout bij opslaan actie: Fout bij opslaan actie: <div style="clear:both">&nbsp;</div><div class="queries" style="clear:both; margin_bottom:2px; border: red dotted thin;">Queries made or created this session were<br/> <ol> <li>Raw query: INSERT INTO wp_actionscheduler_actions ( `hook`, `status`, `scheduled_date_gmt`, `scheduled_date_local`, `schedule`, `group_id`, `args` ) SELECT 'woocommerce_cleanup_draft_orders', 'pending', '2023-02-22 19:31:16', '2023-02-22 19:31:16', 'O:32:\"ActionScheduler_IntervalSchedule\":5:{s:22:\"\0*\0scheduled_timestamp\";i:1677094276;s:18:\"\0*\0first_timestamp\";i:1677094276;s:13:\"\0*\0recurrence\";i:86400;s:49:\"\0ActionScheduler_IntervalSchedule\0start_timestamp\";i:1677094276;s:53:\"\0ActionScheduler_IntervalSchedule\0interval_in_seconds\";i:86400;}', 0, '[]' FROM DUAL WHERE ( SELECT NULL FROM DUAL ) IS NULL</li> <li>Rewritten: INSERT INTO wp_actionscheduler_actions ( hook, status, scheduled_date_gmt, scheduled_date_local, schedule, group_id, args ) SELECT 'woocommerce_cleanup_draft_orders', 'pending', '2023-02-22 19:31:16', '2023-02-22 19:31:16', 'O:32:\"ActionScheduler_IntervalSchedule\":5:{s:22:\"\0*\0scheduled_timestamp\";i:1677094276;s:18:\"\0*\0first_timestamp\";i:1677094276;s:13:\"\0*\0recurrence\";i:86400;s:49:\"\0ActionScheduler_IntervalSchedule\0start_timestamp\";i:1677094276;s:53:\"\0ActionScheduler_IntervalSchedule\0interval_in_seconds\";i:86400;}', 0, '[]' FROM DUAL WHERE ( SELECT NULL FROM DUAL ) IS NULL</li> <li>With Placeholders: INSERT INTO wp_actionscheduler_actions ( hook, status, scheduled_date_gmt, scheduled_date_local, schedule, group_id, args ) SELECT :param_0 , :param_1 , :param_2 , :param_3 , :param_4 , 0, :param_5 FROM DUAL WHERE ( SELECT NULL FROM DUAL ) IS NULL</li> <li>Prepare: INSERT INTO wp_actionscheduler_actions ( hook, status, scheduled_date_gmt, scheduled_date_local, schedule, group_id, args ) SELECT :param_0 , :param_1 , :param_2 , :param_3 , :param_4 , 0, :param_5 FROM DUAL WHERE ( SELECT NULL FROM DUAL ) IS NULL</li> </ol> </div><div style="clear:both; margin_bottom:2px; border: red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">Error occurred at line 1644 in Function prepare_query. <br/> Error message was: Problem preparing the PDO SQL Statement. Error was: SQLSTATE[HY000]: General error: 1 no such table: DUAL </div><pre>#0 /www/wwwroot/website.com/wp-content/db.php(2746): WP_SQLite_DB\PDOEngine->get_error_message() #1 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(101): WP_SQLite_DB\wpsqlitedb->query('...') #2 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(62): ActionScheduler_DBStore->save_action_to_db(Object(ActionScheduler_Action), NULL, false) #3 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php(31): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action), NULL) #4 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #5 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(244): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #6 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(151): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #7 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(122): ActionScheduler_ActionFactory->recurring_unique('...', Array, false, 86400, '', false) #8 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/DraftOrders.php(65): as_schedule_recurring_action(false, 86400, '...') #9 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/DraftOrders.php(57): Automattic\WooCommerce\Blocks\Domain\Services\DraftOrders->maybe_create_cronjobs() #10 /www/wwwroot/website.com/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Blocks\Domain\Services\DraftOrders->install('') #11 /www/wwwroot/website.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #12 /www/wwwroot/website.com/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #13 /www/wwwroot/website.com/wp-admin/admin.php(175): do_action('...') #14 /www/wwwroot/website.com/wp-admin/index.php(10): require_once('...') </pre> in /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action() #1 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(244): ActionScheduler_HybridStore->save_action() #2 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(151): ActionScheduler_ActionFactory->store() #3 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(122): ActionScheduler_ActionFactory->recurring_unique() #4 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/DraftOrders.php(65): as_schedule_recurring_action() #5 /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/DraftOrders.php(57): Automattic\WooCommerce\Blocks\Domain\Services\DraftOrders->maybe_create_cronjobs() #6 /www/wwwroot/website.com/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Blocks\Domain\Services\DraftOrders->install() #7 /www/wwwroot/website.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #8 /www/wwwroot/website.com/wp-includes/plugin.php(517): WP_Hook->do_action() #9 /www/wwwroot/website.com/wp-admin/admin.php(175): do_action() #10 /www/wwwroot/website.com/wp-admin/index.php(10): require_once('...') #11 {main} thrown in /www/wwwroot/website.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

**Comment by adamziel** [comment]
@Torqain3 this problem is solved in the [WordPress/sqlite-database-integration](https://github.com/WordPress/sqlite-database-integration) plugin ([available in WordPress Plugin Directory](https://wordpress.org/plugins/sqlite-database-integration/)).

See https://github.com/aaemnnosttv/wp-sqlite-db/issues/55 for more context

**Comment by Torqain3** [comment]
@adamziel HOLY! this is amazing, great work!!!!
