### ISSUE TITLE
not be supported in version 6.5 of WordPress.

### ISSUE THREAD

**Issue by lopins** [aaemnnosttv/wp-sqlite-db#63]

**Comment by daniel-affonso-pro** [comment]
Troquei o código da linha **1325**, do arquivo **/wp-content/db.php** pelo código abaixo:
`public function query(string $statement, ?int $mode = PDO::ATTR_DEFAULT_FETCH_MODE, mixed ...$fetchModeArgs)`

O Admin não funciona, mas o Front sim. 

Deve ajudar alguém.

**Comment by aaemnnosttv** [comment]
Please add a description when opening an issue.
